services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: voicecare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/voicecare
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: your-secret-key
      OLLAMA_BASE_URL: http://ollama:11434
    depends_on:
      - db
      - ollama
    ports:
      - "3000:3000"
    command: npm run dev

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/voicecare
      PROVIDER_API_KEY: ${PROVIDER_API_KEY:-}
      LLM_PROVIDER: ${LLM_PROVIDER:-rule-based}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://ollama:11434}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-llama3.2}
      PYTHONUNBUFFERED: "1"
    depends_on:
      - db
      - ollama
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    command: serve

volumes:
  db_data:
  ollama_data:


